export const LOAD_TIMELINE = 'PORTFOLIO/AboutmePage/LOAD_TIMELINE';
export const LOAD_TIMELINE_SUCCESS =
  'PORTFOLIO/AboutmePage/LOAD_TIMELINE_SUCCESS';
export const LOAD_TIMELINE_ERROR = 'PORTFOLIO/AboutmePage/LOAD_TIMELINE_ERROR';
export const LOAD_PARAGRAPH = 'PORTFOLIO/AboutmePage/LOAD_PARAGRAPH';
