export const LOAD_SKILLS = 'PORTFOLIO-SITE/SkillsPage/LOAD_SKILLS';
export const LOAD_SKILLS_SUCCESS =
  'PORTFOLIO-SITE/SkillsPage/LOAD_SKILLS_SUCCESS';
export const LOAD_SKILLS_ERROR = 'PORTFOLIO-SITE/SkillsPage/LOAD_SKILLS_ERROR';
